### ISSUE TITLE
anyone can edit anyone group

### ISSUE THREAD

**Issue by UAEpro** [Doc94/TS3IconManager#1]
you can edit any client by getting there unique id

**Comment by Doc94** [comment]
Yes, it is a defect for which this script is not used in production for given ranges of certain privileges. Since the solution to this would be to implement a BOT to confirm and use a system of accounts.
Even so this script asks you should be connected to ts as a small measure to prevent use in people afk ...

**Comment by Doc94** [comment]
Add System of Confirmation for change of icons.
